<?php

/**
 * Implementation of hook_menu_alter().
 *
 * This alther puts tabs for the user profile in this order
 * view (named about, core)
 * Research (views)
 * Publications (biblio)
 * Courses (views)
 * Contact (contact module)
 * Edit (core)
 * Shortcuts (core)
 * Devel (devel)
 */
function c4s_custom_menu_alter(&$items) {
  // Set the user weights
  $items['user/%user/biblio']['weight'] = 4;
  $items['user/%user/biblio']['title'] = 'Publications';
  $items['user/%user/contact']['weight'] = 8;
  $items['user/%user/edit']['weight'] = 10;
}

/**
 * Implementation of hook_block_info().
 *
 * Creates a login link
 */
function c4s_custom_block_info() {
  $blocks['user_login_link'] = array(
    'info' => t('Login Link'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implementation of hook_block_view().
 *
 */
function c4s_custom_block_view($delta = '') {
  switch ($delta) {
    case 'user_login_link':
      $block['content'] = l(t('Log in'), 'user');
      break;
  }
  return $block;
}

/**
 * Implementation of hook_page_build().
 *
 * Change user/%user/biblio page title
 */
function c4s_custom_page_build(&$page) {
  if (arg(0) == 'user' && is_numeric(arg(1)) && arg(2) == 'biblio') {
    drupal_set_title(t('Publications'));
  }
}
