<?php

/**
 * Implementation of hook_menu_alter().
 *
 * This alther puts tabs for the user profile in this order
 * view (named about, core)
 * Research (views)
 * Publications (biblio)
 * Courses (views)
 * Contact (contact module)
 * Edit (core)
 * Shortcuts (core)
 * Devel (devel)
 */
function c4s_custom_menu_alter(&$items) {
  // Set the user weights
  $items['user/%user/biblio']['weight'] = 4;
  $items['user/%user/biblio']['title'] = 'Publications';
  $items['user/%user/contact']['weight'] = 8;
  $items['user/%user/edit']['weight'] = 10;
  $items['user/%user/shortcuts']['weight'] = 12;
}

