<?php

function og_viewscontext_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_pre_render().
 */
function og_viewscontext_views_post_execute(&$view) {
  if ($view->name == 'group_menu') {
    $results = $view->result;
    foreach ($results as $rowid => $result) {
      foreach ($result->{'field_' . OG_GROUP_MENU_FIELD} as $delta => &$field) {
        $url = $field['raw']['url'];
        $parts = parse_url($url);
        if ($parts['host'] == $_SERVER[ 'SERVER_NAME' ]) {
          $path = ltrim($parts['path'], '/');
          if (drupal_lookup_path('source', $path)) $path = drupal_lookup_path ('source', $path);
          if (!drupal_valid_path($path)) {
            //unset($result->{'field_' . OG_GROUP_MENU_FIELD}[$delta]);
            //$field['rendered']['#access'] = FALSE;
            unset($view->result[$rowid]);
          }
        }
      }
    }
  }
}

/**
 * View access callback
 * With new og-7.x-2.x, $use_nid is no longer used
 */
function og_viewscontext_access_group_member_access($arg_pos, $use_nid = FALSE) {
  $arg = arg($arg_pos);
  $gid = 0;
  if (!isset($arg) || !is_numeric($arg)) {
    return FALSE;
  }
  $gid = $arg;

  if ($arg == 0)    return FALSE;

  return og_is_member('node', $gid) || user_access('administer group') || og_user_access('node', $gid, 'adminster group');
}
