<?php

function aacr_biblio_migrate_api() {
  $api = array(
    'api' => '2',
    'migrations' => array(
      'AACRBiblioMigrate' => array('class_name' => 'AACRBiblioMigrate'),
      'AACRBiblioKeywords' => array('class_name' => 'AACRBiblioKeywords'),
      'AACRBiblioContributers' => array('class_name' => 'AACRBiblioContributers'),
      'AACRBiblioContributersJoin' => array('class_name' => 'AACRBiblioContributersJoin'),
    ),
  );
  
  return $api;
}
